CREATE DATABASE QUANLYKHACHSAN

CREATE TABLE PHONG
(
	MAPHONG INT IDENTITY(1,1) PRIMARY KEY,
	MALP VARCHAR(4),
	TENPHONG NVARCHAR(20),
	GHICHU NVARCHAR(40),
	TRANGTHAI NVARCHAR(20),
)

CREATE TABLE LOAIPHONG
(
	MALP VARCHAR(4) PRIMARY KEY,
	TENLOAIPHONG NVARCHAR(20),
	DONGIA MONEY
)

CREATE TABLE CHITIETPTP
(
	MACTPTP INT IDENTITY(1,1) PRIMARY KEY,
	MAPTP INT,
	MAKH int,
)

CREATE TABLE PHIEUTHUEPHONG
(
	MAPTP INT IDENTITY(1,1) PRIMARY KEY,
	MAPHONG INT,
	NGAYLAP DATETIME,
	SOLUONG INT,
	DONGIA MONEY
	TINHTRANG nvarchar(30)
)


CREATE TABLE KHACHHANG
(
	MAKH INT IDENTITY(1,1) PRIMARY KEY,
	MALK VARCHAR(4),
	TENKH NVARCHAR(40),
	CMND VARCHAR(12),
	DIACHI NVARCHAR(144),
)

CREATE TABLE LOAIKHACH
(
	MALK VARCHAR(4) PRIMARY KEY,
	TENLOAIKHACH NVARCHAR(20)
)

CREATE TABLE HOADON
(
	MAHD INT IDENTITY(1,1) PRIMARY KEY,
	MAKH int,
	NGAYLAP DATETIME,
	TONGTIEN MONEY	
)

CREATE TABLE CHITIETHD
(
	MACTHD INT IDENTITY(1,1) PRIMARY KEY,
	MAPTP INT,
	MAHD INT,
	MADV INT,
	SONGAYTHUE INT
)

CREATE TABLE DICHVU
(
	MADV INT IDENTITY(1,1) PRIMARY KEY,
	TENDV NVARCHAR(20),
	DONGIA MONEY
)

CREATE TABLE CHITIETTHANHTOAN
(
	MAHD INT,
	MAKH int,
	MALHTT INT,
	CONSTRAINT PK_KHACHDAT PRIMARY KEY(MAHD, MAKH, MALHTT)
)

CREATE TABLE LOAIHINHTHANHTOAN
(
	MALHTT INT IDENTITY(1,1) PRIMARY KEY,
	TENLHTT NVARCHAR(20),
)

CREATE TABLE CTBAOCAODOANHTHU
(
	MACTBCDT INT IDENTITY(1,1) PRIMARY KEY,
	MALP VARCHAR(4),
	MABCDT INT,
	DOANHTHU MONEY,
	TYLE FLOAT
)

CREATE TABLE BAOCAODOANHTHU
(
	MABCDT INT IDENTITY(1,1) PRIMARY KEY,
	TENBAOCAO NVARCHAR(20),
	NGAYLAP DATETIME,
	THANGBAOCAO INT,
	NAMBAOCAO int
)

CREATE TABLE TAIKHOAN
(
	MATK INT IDENTITY(1,1) PRIMARY KEY,
	MALOAITK INT,
	TENCHUTAIKHOAN NVARCHAR(20),
	TENDANGNHAP VARCHAR(20),
	MATKHAU VARCHAR(90),
)

CREATE TABLE PHANLOAITAIKHOAN
(
	MALOAITK INT IDENTITY(1,1) PRIMARY KEY,
	TENLOAITK NVARCHAR(20),
	QUYENHAN NVARCHAR(50)
)

CREATE TABLE THAMSO
(
	MATHAMSO VARCHAR(5) PRIMARY KEY,
	TENTHAMSO NVARCHAR(20),
	GIATRI FLOAT
)


-- Thêm ràng buộc khóa ngoại ở các bảng
ALTER TABLE PHONG ADD CONSTRAINT FK_PHONG_MALP FOREIGN KEY (MALP) REFERENCES LOAIPHONG(MALP)

ALTER TABLE CHITIETPTP ADD CONSTRAINT FK_CHITIETPTP_MAPTP FOREIGN KEY (MAPTP) REFERENCES PHIEUTHUEPHONG(MAPTP)
ALTER TABLE CHITIETPTP ADD CONSTRAINT FK_CHITIETPTP_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE PHIEUTHUEPHONG ADD CONSTRAINT FK_PHIEUTHUEPHONG_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG)

ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KHACHHANG_MALK FOREIGN KEY (MALK) REFERENCES LOAIKHACH(MALK)

ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_MAPTP FOREIGN KEY (MAPTP) REFERENCES PHIEUTHUEPHONG(MAPTP)
ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE CHITIETHD ADD CONSTRAINT FK_CHITIETHD_MADV FOREIGN KEY (MADV) REFERENCES DICHVU(MADV)

ALTER TABLE CHITIETTHANHTOAN ADD CONSTRAINT FK_THANHTOAN_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE CHITIETTHANHTOAN ADD CONSTRAINT FK_THANHTOAN_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
ALTER TABLE CHITIETTHANHTOAN ADD CONSTRAINT FK_THANHTOAN_MALHTT FOREIGN KEY (MALHTT) REFERENCES LOAIHINHTHANHTOAN(MALHTT)

ALTER TABLE CTBAOCAODOANHTHU ADD CONSTRAINT FK_CTBAOCAODOANHTHU_MALP FOREIGN KEY (MALP) REFERENCES LOAIPHONG(MALP)
ALTER TABLE CTBAOCAODOANHTHU ADD CONSTRAINT FK_CTBAOCAODOANHTHU_MABCDT FOREIGN KEY (MABCDT) REFERENCES BAOCAODOANHTHU(MABCDT)

ALTER TABLE TAIKHOAN ADD CONSTRAINT FK_TAIKHOAN_MALOAITK FOREIGN KEY (MALOAITK) REFERENCES PHANLOAITAIKHOAN(MALOAITK)

insert into PHANLOAITAIKHOAN(TENLOAITK,QUYENHAN) values('Quản trị viên','mọi thứ')
insert into TAIKHOAN(MALOAITK,TENCHUTAIKHOAN,TENDANGNHAP,MATKHAU) VALUES (1,'WIBU LORD','ADMIN','6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b')

INSERT INTO PHANLOAITAIKHOAN(TENLOAITK,QUYENHAN) VALUES ('ADMIN',N'Quản trị viên')
INSERT INTO PHANLOAITAIKHOAN(TENLOAITK,QUYENHAN) VALUES (N'Nhân viên',N'Lễ tân')

set dateformat DMY

insert into LOAIKHACH(MALK, TENLOAIKHACH) values ('NN', N'Nước ngoài')
insert into LOAIKHACH(MALK, TENLOAIKHACH) values ('ND', N'Nội địa')


insert into THAMSO(MATHAMSO, TENTHAMSO, GIATRI) values ('TS1', N'SOKHACHTOIDA', 3)
insert into THAMSO(MATHAMSO, TENTHAMSO, GIATRI) values ('TS2', N'HESOPHUTHU', 1.5)
insert into THAMSO(MATHAMSO, TENTHAMSO, GIATRI) values ('TS3', N'TYLEPHUTHU', 25)
insert into THAMSO(MATHAMSO, TENTHAMSO, GIATRI) values ('TS4', N'TIENLE', 30000)
insert into THAMSO(MATHAMSO, TENTHAMSO, GIATRI) values ('TS5', N'KHUYENMAI', 10)

DELETE FROM THAMSO

select * from THAMSO

insert into DICHVU(TENDV, DONGIA) values (N'Giặt ủi', 100000)
insert into DICHVU(TENDV, DONGIA) values (N'Trông trẻ', 200000)
insert into DICHVU(TENDV, DONGIA) values (N'Phục vụ phòng', 500000)
insert into DICHVU(TENDV, DONGIA) values (N'Giao hàng', 100000)


insert into LOAIHINHTHANHTOAN(TENLHTT) values (N'Tiền mặt')
insert into LOAIHINHTHANHTOAN(TENLHTT) values (N'Chuyển khoản')


select * from PHIEUTHUEPHONG

select * from CHITIETPTP

select * from HOADON

select * from THAMSO

select * from DICHVU

select * from BAOCAODOANHTHU

select * from CTBAOCAODOANHTHU

delete from BAOCAODOANHTHU

delete from CTBAOCAODOANHTHU 

delete from CHITIETHD

delete from HOADON

select * from THAMSO

delete * from CHITIETPTP

select A.MAPTP, MAPHONG, NGAYLAP, SOLUONG, FORMAT(DONGIA, '###,###') 'DONGIA', TENKH, B.MAKH 
from PHIEUTHUEPHONG A 
inner join CHITIETPTP B on A.MAPTP = B.MAPTP 
inner join KHACHHANG C on B.MAKH = C.MAKH
group by A.MAPTP


select MAPTP, A.MAPHONG, NGAYLAP, SOLUONG, FORMAT(DONGIA, '###,###') 'DONGIA', TENKH, MAKH, TINHTRANG
from 
( 
	SELECT  A.MAPTP, MAPHONG, NGAYLAP, SOLUONG,DONGIA, TENKH, TINHTRANG, B.MAKH,RANK() OVER (PARTITION BY A.MAPTP ORDER BY MAX(B.MAKH) ASC) AS XEPHANG 
	from PHIEUTHUEPHONG A 
	inner join CHITIETPTP B on A.MAPTP = B.MAPTP 
	inner join KHACHHANG C on B.MAKH = C.MAKH 
	where TINHTRANG = N'Chưa thanh toán'
	group by A.MAPTP, MAPHONG, NGAYLAP, SOLUONG,DONGIA, TENKH, B.MAKH, TINHTRANG
) as A 
inner join PHONG on A.MAPHONG = PHONG.MAPHONG
where XEPHANG=1 

select * from PHIEUTHUEPHONG

select * from PHONG where MALP = 'A'





